//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diagramms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        public int Код_сотрудника { get; set; }
        public int Код_труда { get; set; }
        public System.DateTime Дата_и_время { get; set; }
    
        public virtual Билет Билет { get; set; }
        public virtual дата_найма дата_найма { get; set; }
        public virtual Оплата_труда Оплата_труда { get; set; }
    }
}
