//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace work_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.Оформленный_рейс = new HashSet<Оформленный_рейс>();
        }
    
        public int Roles { get; set; }
        public string email { get; set; }
        public string PasswordD { get; set; }
        public string NAMEE { get; set; }
        public string LASTNAME { get; set; }
        public string CITY { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string ACTIVE { get; set; }
        public string role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Оформленный_рейс> Оформленный_рейс { get; set; }
    }
}
