//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace work_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Информация_о_рейсах
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Информация_о_рейсах()
        {
            this.Commands = new HashSet<Command>();
        }
    
        public int Код_самолета { get; set; }
        public int Код_персонала { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Command> Commands { get; set; }
        public virtual РЕЙСЫ РЕЙСЫ { get; set; }
        public virtual Самолеты Самолеты { get; set; }
    }
}
