//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace work_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оформленный_рейс
    {
        public int Должность { get; set; }
        public int Код_рейса { get; set; }
        public Nullable<System.DateTime> Дата_оформления { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual РЕЙСЫ РЕЙСЫ { get; set; }
    }
}
