//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace work_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class РЕЙСЫ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public РЕЙСЫ()
        {
            this.Информация_о_рейсах = new HashSet<Информация_о_рейсах>();
            this.Оформленный_рейс = new HashSet<Оформленный_рейс>();
        }
    
        public int Код_рейса { get; set; }
        public string Название_рейса { get; set; }
        public string Место_локации { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Информация_о_рейсах> Информация_о_рейсах { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Оформленный_рейс> Оформленный_рейс { get; set; }
    }
}
