//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace work_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Самолеты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Самолеты()
        {
            this.Информация_о_рейсах = new HashSet<Информация_о_рейсах>();
        }
    
        public int Код_самолета { get; set; }
        public string номер { get; set; }
        public string бортовой_номер { get; set; }
        public string Лицензия { get; set; }
        public string специализация { get; set; }
        public string Компания_производитель { get; set; }
        public string Домашний_адрес { get; set; }
        public string номер_двигателя { get; set; }
        public Nullable<System.DateTime> Начало_эксплуатации { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Информация_о_рейсах> Информация_о_рейсах { get; set; }
    }
}
